### ISSUE TITLE
Use Jobs API to show generation progress

### ISSUE THREAD

**Issue by Taneb** [Taneb/ecore2thrift#11]
Currently it is unclear if it's taking a while or going at all.

**Comment by agarciadom** [comment]
Here is some documentation on the Jobs API for Eclipse:

http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fruntime_jobs.htm

You only need to extend Job with your own run() method that wraps your EVL/EGL logic and then instantiate and schedule the job from your current handler.
