### ISSUE TITLE
Add validation layer

### ISSUE THREAD

**Issue by Taneb** [Taneb/ecore2thrift#3]
Use EVL to validate the EMF file before applying the EGL translation.
- [x] EClass instances cannot have operations which share a name with Thrift reserved words
- [x] EClasses should only have structural features and attributes (ie., be  a structure or exception), or only operations (ie., be a service)
- [x] ~~An EClass should not have any references~~ This one had some oddities to do with lists and types called reference, won't fix (for now)
- [x] If an EClass has been used as an exception, warn if it is also used as a struct
- [x] Two fields or arguments or exceptions cannot have the same value in the 'n' field of a @thrift(n=...) annotation
- [x] Warn if there is an unused struct or exception
- [x] @thrift(n) annottions should only be used on arguments, fields, and exceptions, and should have an (non-negative) integer value
- [x] @thrift(javans) should only be usable on packages, and should be a valid Java package name
- [x] @doc(auth) should only be used on operations, and the value should be a boolean
- [x] @doc(optional) should only be used on arguments, and the value should be a boolean
- [x] A field's type must be a valid Thrift type

**Comment by agarciadom** [comment]
Don't forget to push your contributions periodically. A few smaller commits are easier to review than one huge commit :-).
